# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings


from backend_server.grpc_config import msg_transfer_pb2 as msg__transfer__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in msg_transfer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class MsgTransferStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.image_processor = channel.unary_unary(
                '/MsgTransfer/image_processor',
                request_serializer=msg__transfer__pb2.MsgRequest.SerializeToString,
                response_deserializer=msg__transfer__pb2.MsgReply.FromString,
                _registered_method=True)
        self.get_server_utilization = channel.unary_unary(
                '/MsgTransfer/get_server_utilization',
                request_serializer=msg__transfer__pb2.Server_Utilization_Request.SerializeToString,
                response_deserializer=msg__transfer__pb2.Server_Utilization_Reply.FromString,
                _registered_method=True)
        self.get_loaded_models_name = channel.unary_unary(
                '/MsgTransfer/get_loaded_models_name',
                request_serializer=msg__transfer__pb2.Loaded_Model_Name_Request.SerializeToString,
                response_deserializer=msg__transfer__pb2.Loaded_Model_Name_Reply.FromString,
                _registered_method=True)
        self.load_specified_model = channel.unary_unary(
                '/MsgTransfer/load_specified_model',
                request_serializer=msg__transfer__pb2.Load_Specified_Model_Request.SerializeToString,
                response_deserializer=msg__transfer__pb2.Load_Specified_Model_Reply.FromString,
                _registered_method=True)


class MsgTransferServicer(object):
    """Missing associated documentation comment in .proto file."""

    def image_processor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_server_utilization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_loaded_models_name(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def load_specified_model(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MsgTransferServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'image_processor': grpc.unary_unary_rpc_method_handler(
                    servicer.image_processor,
                    request_deserializer=msg__transfer__pb2.MsgRequest.FromString,
                    response_serializer=msg__transfer__pb2.MsgReply.SerializeToString,
            ),
            'get_server_utilization': grpc.unary_unary_rpc_method_handler(
                    servicer.get_server_utilization,
                    request_deserializer=msg__transfer__pb2.Server_Utilization_Request.FromString,
                    response_serializer=msg__transfer__pb2.Server_Utilization_Reply.SerializeToString,
            ),
            'get_loaded_models_name': grpc.unary_unary_rpc_method_handler(
                    servicer.get_loaded_models_name,
                    request_deserializer=msg__transfer__pb2.Loaded_Model_Name_Request.FromString,
                    response_serializer=msg__transfer__pb2.Loaded_Model_Name_Reply.SerializeToString,
            ),
            'load_specified_model': grpc.unary_unary_rpc_method_handler(
                    servicer.load_specified_model,
                    request_deserializer=msg__transfer__pb2.Load_Specified_Model_Request.FromString,
                    response_serializer=msg__transfer__pb2.Load_Specified_Model_Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MsgTransfer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MsgTransfer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MsgTransfer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def image_processor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MsgTransfer/image_processor',
            msg__transfer__pb2.MsgRequest.SerializeToString,
            msg__transfer__pb2.MsgReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_server_utilization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MsgTransfer/get_server_utilization',
            msg__transfer__pb2.Server_Utilization_Request.SerializeToString,
            msg__transfer__pb2.Server_Utilization_Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_loaded_models_name(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MsgTransfer/get_loaded_models_name',
            msg__transfer__pb2.Loaded_Model_Name_Request.SerializeToString,
            msg__transfer__pb2.Loaded_Model_Name_Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def load_specified_model(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MsgTransfer/load_specified_model',
            msg__transfer__pb2.Load_Specified_Model_Request.SerializeToString,
            msg__transfer__pb2.Load_Specified_Model_Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
